#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
POSTGRES_PASSWORD = data.get("POSTGRES_PASSWORD", "password") 
POSTGRES_USER = data.get("POSTGRES_USER", "dokploy") 
POSTGRES_DB = data.get("POSTGRES_DB", "dokploy") 
 
postgres = { 
 "POSTGRES_PASSWORD" : POSTGRES_PASSWORD ,
 "POSTGRES_USER" : POSTGRES_USER ,
 "POSTGRES_DB" : POSTGRES_DB ,
} 
agent.write_envfile("postgres.env", postgres) 
