#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail
exec 1>&2 # Redirect any output to the journal (stderr)

# Prepare an initialization script that restores the dump file
mkdir -vp restore
cat - >restore/dokploy_restore.sh <<'EOS'
# Read dump file from standard input:
pg_restore --no-owner --no-privileges -U dokploy -d dokploy
ec=$?
docker_temp_server_stop
exit $ec
EOS

# once we exit we remove initdb.d
trap 'rm -rfv initdb.d/' EXIT

# we start a container to initiate a database and load the dump
# at the end of dokploy_restore.sh the dump is loaded and
# we exit the container
podman run \
	--rm \
	--interactive \
	--network=none \
	--volume=./restore:/docker-entrypoint-initdb.d/:Z \
	--volume=postgres-data:/var/lib/postgresql/data:Z \
	--replace --name=restore_db \
	--env-file postgres.env \
	--env TZ=UTC \
	"${POSTGRES_IMAGE}" <dokploy.pg_dump

# If the restore is successful, clean up:
rm -rfv restore/ dokploy.pg_dump